### ISSUE TITLE
Parallelization optimization utilizing OpenMP is not significant enough

### ISSUE THREAD

**Issue by brandontrama** [ColeMcGregor/ParallelProcessingFinalProject#10]
While attempting to implement OpenMP, increasing the number of threads does not significantly improve computation time to justify parallelization in the first place. Typical times range from ~11-13 seconds for any given number of threads.

With this observation, I present two questions:

* Is the current optimization of OpenMP structured optimally?
* What alternative strategies could be used for parallelization that could solve this issue?

Embedded below are the code snippets of the parallelization taking place:

`Simulation.cpp` - where the calculation of bodies are split up between threads

https://github.com/ColeMcGregor/ParallelProcessingFinalProject/blob/013694959058bed370c757b301adea7dd96b321b/src/Simulation/Simulation.cpp#L61-L128
`body.cpp` - sumForces uses a custom reduction `vector_reduction` to accumulate forces parallelly
https://github.com/ColeMcGregor/ParallelProcessingFinalProject/blob/013694959058bed370c757b301adea7dd96b321b/src/Simulation/body.cpp#L121-L139

**Comment by jteresco** [comment]
Are you running on noreaster or Stampede3 or somewhere else?  

Looking specifically at the first part, my first thought is that the threads aren't really being create as expected and/or scheduled to run concurrently for some reason.  What happens when you include those extra printouts that are commented out?  Are you seeing evidence of threads being created?  Also if on noreaster, open up a second terminal and run the `top` command to see if you're getting more than 100% CPU (should be 400% for 4 threads) for your process.

**Comment by brandontrama** [comment]
I am running this on stampede. The extra printouts do show that threads are being created and work on their own bodies. I decided to test changing `schedule(dynamic)` to `schedule(static)`,  on line 75 in the current version of `Simulation.cpp`, and that seems to have fixed the problem as now we are getting faster times when increasing threads. However, I did change it back to dynamic and am testing how well dynamic works if I specify how many bodies a thread can handle at once via `chunk_size`.

https://github.com/ColeMcGregor/ParallelProcessingFinalProject/blob/b7ac81fc9095c9400059722ae8cee4dd3a15e17a/src/Simulation/Simulation.cpp#L58-L59
https://github.com/ColeMcGregor/ParallelProcessingFinalProject/blob/b7ac81fc9095c9400059722ae8cee4dd3a15e17a/src/Simulation/Simulation.cpp#L75

**Comment by brandontrama** [comment]
As a follow up, using 4 threads on noreaster uses 400% usage.

**Comment by jteresco** [comment]
Sounds like good news.  I would have thought the dynamic would work but apparently not.

**Comment by brandontrama** [comment]
Thank you for taking your time to look over this issue for me, the `top` command is also super useful too. I think for now this issue has been resolved.
